### ISSUE TITLE
Q: Where should I place the mocks in my test?

### ISSUE THREAD

**Issue by astyagun** [andreareginato/betterspecs#128]
```ruby
describe '#method1' do
  before { expect(SomeClass).to receive(:method2) }
  subject { described_class.new.method1 }

  it 'calls SomeClass.method2' do
    subject
  end
end
```

VS

```ruby
describe '#method1' do
  subject { described_class.new.method1 }

  it 'calls SomeClass.method2' do
    expect(SomeClass).to receive(:method2)
    subject
  end
end
```

**Comment by astyagun** [comment]
Thanks @geniou, we've had an argument about this at work and your solution satisfies both sides :)

**Comment by geniou** [comment]
@astyagun your welcome. :)

**Comment by onebree** [comment]
@astyagun if your issue has been resolved, please close it. Otherwise, I am leaving it open.

In the future, I plan to have a forum or chat for questions like this, as they can be solved soon. (Like this one was.) When we overhaul the site, issues will be general questions on best practice or about the code.... not personal cases of "what's best to do"
