### ISSUE TITLE
Add links swich different languages

### ISSUE THREAD

**Issue by andreareginato** [andreareginato/betterspecs#65]
On the top menu (probably on the right) we need to insert the capability to choose different languages for better specs. Rght now we have korean and russian translations.

**Comment by onebree** [comment]
When we change the format of the site, we can haven links to the country flag, which points the user to a translated version of the site. This is why Pages would be good, because it will be easier to format other languages (using `**` for bold) and to render partials dependent on a parameter passed to the URL (like `[language]=de`)

**Comment by onebree** [comment]
I just found that this issue was referenced by a merge pull request (#70), so I am closing this issue now.
