### ISSUE TITLE
Expect vs Should syntax

### ISSUE THREAD

**Issue by maurogeorge** [andreareginato/betterspecs#83]
In the [following text](http://myronmars.to/n/dev-blog/2013/07/the-plan-for-rspec-3#what_about_the_old_expectationmock_syntax) Myron says to use this on new projects.

You guys think this is a good section to better specs? I personaly have use this on new projects with configuration to use only new syntax.

**Comment by mltsy** [comment]
I agree that `expect` is the correct syntax to use for block expectations, but for one-liners, it's actually still perfectly okay to use `should`, as it's a method from a different class entirely (it's not the same `should`) and it sounds and looks much better than `it { is_expected.to ... }`.  The only reason the other `should` was removed was because it required monkey-patching `Object`.  That is not the case with this `should`, and it [has not been removed as of RSpec 3.4](https://relishapp.com/rspec/rspec-core/docs/subject/one-liner-syntax), and doesn't look like it will be.

I think both syntaxes for one-liners should be on the "GOOD" list.

**Comment by Argus9** [comment]
+1 at @mltsy's point. Are we crossing wires here? I feel like `should` reads a lot better than `is_expected.to` in one-liner cases.

**Comment by kigster** [comment]
I’m sorry for being blunt here, but I think this whole expect vs should is horse shit.

Why remove should? It means the same thing. There is a reason we have synonyms in English language. 

I love should and use it and will keep using it. And when 4 removes it I will add an alias. 

This is dumb stupid religious dog fighting. Why not have it both ways?

**Comment by philipfong** [comment]
@kigster do you have any guidance on how to set an alias when it is officially removed? I am a little lost as to how to maintain `should` syntax.

**Comment by kigster** [comment]
Since these are likely simple methods you can just alias them like this, say in ruby:

```
  def alias(...)
     original(*, **, &block)
  end
```

But I don't think you need to worry about it. It's ok to break the API as long you increment the major version and document it in the CHANGELOG.
